[2021-09-08 19:36:00,516] INFO [GroupCoordinator 0]: Member consumer-mygroup-2-8642a485-24d9-4b31-a23c-6b83d052efb1 in group mygroup has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-09-08 19:36:00,613] WARN Attempting to send response via channel for which there is no open connection, connection id 127.0.0.1:9092-127.0.0.1:64174-43 (kafka.network.Processor)
[2021-09-08 19:36:03,644] INFO [GroupCoordinator 0]: Preparing to rebalance group mygroup in state PreparingRebalance with old generation 243 (__consumer_offsets-39) (reason: removing member consumer-mygroup-2-8642a485-24d9-4b31-a23c-6b83d052efb1 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2021-09-08 19:36:03,648] INFO [GroupCoordinator 0]: Member consumer-mygroup-1-b1cd0d7f-38e1-4df8-96cf-d7950a0cba6d in group mygroup has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-09-08 19:36:00,645] INFO Expiring session 0x100822595950004, timeout of 18000ms exceeded (org.apache.zookeeper.server.ZooKeeperServer)
[2021-09-08 19:36:03,667] INFO [GroupCoordinator 0]: Member consumer-mygroup-1-7a9f4ece-b53c-48ef-9ff9-bd1c9d6e029c in group mygroup has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-09-08 19:36:03,669] INFO [GroupCoordinator 0]: Group mygroup with generation 244 is now empty (__consumer_offsets-39) (kafka.coordinator.group.GroupCoordinator)
[2021-09-08 19:36:03,698] INFO [GroupCoordinator 0]: Preparing to rebalance group mygroup in state PreparingRebalance with old generation 244 (__consumer_offsets-39) (reason: Adding new member consumer-mygroup-2-750691e9-f7b1-4994-9756-35a0729a4dcb with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-09-08 19:36:03,704] INFO [GroupCoordinator 0]: Stabilized group mygroup generation 245 (__consumer_offsets-39) (kafka.coordinator.group.GroupCoordinator)
[2021-09-08 19:36:03,710] WARN Client session timed out, have not heard from server in 4670652ms for sessionid 0x100822595950004 (org.apache.zookeeper.ClientCnxn)
[2021-09-08 19:36:03,712] INFO Client session timed out, have not heard from server in 4670652ms for sessionid 0x100822595950004, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2021-09-08 19:36:03,962] INFO [GroupCoordinator 0]: Assignment received from leader for group mygroup for generation 245 (kafka.coordinator.group.GroupCoordinator)
[2021-09-08 19:36:05,458] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-08 19:36:05,460] INFO Socket connection established, initiating session, client: /0:0:0:0:0:0:0:1:49887, server: localhost/0:0:0:0:0:0:0:1:2181 (org.apache.zookeeper.ClientCnxn)
[2021-09-08 19:36:05,463] INFO Invalid session 0x100822595950004 for client /0:0:0:0:0:0:0:1:49887, probably expired (org.apache.zookeeper.server.ZooKeeperServer)
[2021-09-08 19:36:05,465] WARN Unable to reconnect to ZooKeeper service, session 0x100822595950004 has expired (org.apache.zookeeper.ClientCnxn)
[2021-09-08 19:36:05,466] INFO [ZooKeeperClient Kafka server] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2021-09-08 19:36:05,466] INFO EventThread shut down for session: 0x100822595950004 (org.apache.zookeeper.ClientCnxn)
[2021-09-08 19:36:05,468] INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181. (kafka.zookeeper.ZooKeeperClient)
[2021-09-08 19:36:05,466] INFO Unable to reconnect to ZooKeeper service, session 0x100822595950004 has expired, closing socket connection (org.apache.zookeeper.ClientCnxn)
[2021-09-08 19:36:05,470] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=18000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@6973b51b (org.apache.zookeeper.ZooKeeper)
[2021-09-08 19:36:05,474] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
[2021-09-08 19:36:05,476] INFO zookeeper.request.timeout value is 0. feature enabled= (org.apache.zookeeper.ClientCnxn)
[2021-09-08 19:36:05,482] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-08 19:36:05,483] INFO Socket connection established, initiating session, client: /127.0.0.1:49890, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn)
[2021-09-08 19:36:05,485] INFO Creating /brokers/ids/0 (is it secure? false) (kafka.zk.KafkaZkClient)
[2021-09-08 19:36:05,548] INFO Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x100822595950005, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
[2021-09-08 19:36:05,553] INFO Updated cache from existing FinalizedFeaturesAndEpoch(features=Features{}, epoch=0) to latest FinalizedFeaturesAndEpoch(features=Features{}, epoch=0). (kafka.server.FinalizedFeatureCache)
[2021-09-08 19:36:05,646] INFO Stat of the created znode at /brokers/ids/0 is: 411,411,1631109965551,1631109965551,1,0,0,72200691972898821,202,0,411
 (kafka.zk.KafkaZkClient)
[2021-09-08 19:36:05,647] INFO Registered broker 0 at path /brokers/ids/0 with addresses: PLAINTEXT://localhost:9092, czxid (broker epoch): 411 (kafka.zk.KafkaZkClient)
[2021-09-08 22:51:27,593] INFO [GroupCoordinator 0]: Member consumer-mygroup-1-963a1bd2-b8a0-4cbe-ad6d-950ad5b95f47 in group mygroup has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-09-08 22:51:28,482] INFO [GroupCoordinator 0]: Preparing to rebalance group mygroup in state PreparingRebalance with old generation 245 (__consumer_offsets-39) (reason: removing member consumer-mygroup-1-963a1bd2-b8a0-4cbe-ad6d-950ad5b95f47 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2021-09-08 22:51:28,498] INFO [GroupCoordinator 0]: Member consumer-mygroup-2-750691e9-f7b1-4994-9756-35a0729a4dcb in group mygroup has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-09-08 22:51:28,512] INFO [GroupCoordinator 0]: Stabilized group mygroup generation 246 (__consumer_offsets-39) (kafka.coordinator.group.GroupCoordinator)
[2021-09-08 22:51:28,512] INFO [GroupCoordinator 0]: Preparing to rebalance group mygroup in state PreparingRebalance with old generation 246 (__consumer_offsets-39) (reason: Adding new member consumer-mygroup-1-9dadc61c-5e54-4cf1-9dcc-6a54fcf84e17 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-09-08 22:51:28,527] INFO [GroupCoordinator 0]: Stabilized group mygroup generation 247 (__consumer_offsets-39) (kafka.coordinator.group.GroupCoordinator)
[2021-09-08 22:51:28,795] INFO [GroupCoordinator 0]: Assignment received from leader for group mygroup for generation 247 (kafka.coordinator.group.GroupCoordinator)
[2021-09-08 22:51:29,155] WARN Client session timed out, have not heard from server in 10804132ms for sessionid 0x100822595950005 (org.apache.zookeeper.ClientCnxn)
[2021-09-08 22:51:29,155] INFO Client session timed out, have not heard from server in 10804132ms for sessionid 0x100822595950005, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2021-09-08 22:51:29,155] WARN Unable to read additional data from client sessionid 0x100822595950005, likely client has closed socket (org.apache.zookeeper.server.NIOServerCnxn)
[2021-09-08 22:51:30,155] INFO Expiring session 0x100822595950005, timeout of 18000ms exceeded (org.apache.zookeeper.server.ZooKeeperServer)
[2021-09-08 22:51:30,578] INFO [ProducerStateManager partition=__consumer_offsets-39] Writing producer snapshot at offset 321 (kafka.log.ProducerStateManager)
[2021-09-08 22:51:30,645] INFO [Log partition=__consumer_offsets-39, dir=D:\Workspace\SpringBoot\MB\Kafka\kafka\bin\windows\WorkspaceSpringBootMBKafkakafkadataKafka] Rolled new log segment at offset 321 in 1799 ms. (kafka.log.Log)
[2021-09-08 22:51:30,944] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-08 22:51:30,999] INFO Socket connection established, initiating session, client: /0:0:0:0:0:0:0:1:55393, server: localhost/0:0:0:0:0:0:0:1:2181 (org.apache.zookeeper.ClientCnxn)
[2021-09-08 22:51:31,001] INFO Invalid session 0x100822595950005 for client /0:0:0:0:0:0:0:1:55393, probably expired (org.apache.zookeeper.server.ZooKeeperServer)
[2021-09-08 22:51:31,010] WARN Unable to reconnect to ZooKeeper service, session 0x100822595950005 has expired (org.apache.zookeeper.ClientCnxn)
[2021-09-08 22:51:31,010] INFO EventThread shut down for session: 0x100822595950005 (org.apache.zookeeper.ClientCnxn)
[2021-09-08 22:51:31,010] INFO [ZooKeeperClient Kafka server] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2021-09-08 22:51:31,012] INFO Unable to reconnect to ZooKeeper service, session 0x100822595950005 has expired, closing socket connection (org.apache.zookeeper.ClientCnxn)
[2021-09-08 22:51:31,014] INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181. (kafka.zookeeper.ZooKeeperClient)
[2021-09-08 22:51:31,016] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=18000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@6973b51b (org.apache.zookeeper.ZooKeeper)
[2021-09-08 22:51:31,022] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
[2021-09-08 22:51:31,022] INFO zookeeper.request.timeout value is 0. feature enabled= (org.apache.zookeeper.ClientCnxn)
[2021-09-08 22:51:31,025] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-08 22:51:31,026] INFO Socket connection established, initiating session, client: /0:0:0:0:0:0:0:1:55396, server: localhost/0:0:0:0:0:0:0:1:2181 (org.apache.zookeeper.ClientCnxn)
[2021-09-08 22:51:31,027] INFO Creating /brokers/ids/0 (is it secure? false) (kafka.zk.KafkaZkClient)
[2021-09-08 22:51:31,108] INFO Session establishment complete on server localhost/0:0:0:0:0:0:0:1:2181, sessionid = 0x100822595950006, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
[2021-09-08 22:51:31,113] INFO Updated cache from existing FinalizedFeaturesAndEpoch(features=Features{}, epoch=0) to latest FinalizedFeaturesAndEpoch(features=Features{}, epoch=0). (kafka.server.FinalizedFeatureCache)
[2021-09-08 22:51:31,299] INFO Stat of the created znode at /brokers/ids/0 is: 416,416,1631121691112,1631121691112,1,0,0,72200691972898822,202,0,416
 (kafka.zk.KafkaZkClient)
[2021-09-08 22:51:31,300] INFO Registered broker 0 at path /brokers/ids/0 with addresses: PLAINTEXT://localhost:9092, czxid (broker epoch): 416 (kafka.zk.KafkaZkClient)
[2021-09-09 11:23:33,579] WARN Attempting to send response via channel for which there is no open connection, connection id 127.0.0.1:9092-127.0.0.1:55386-48 (kafka.network.Processor)
[2021-09-09 11:23:33,705] INFO [GroupCoordinator 0]: Member consumer-mygroup-2-b45bc963-787d-448a-aa48-ed96b0f40862 in group mygroup has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-09-09 11:23:35,014] INFO [GroupCoordinator 0]: Preparing to rebalance group mygroup in state PreparingRebalance with old generation 247 (__consumer_offsets-39) (reason: removing member consumer-mygroup-2-b45bc963-787d-448a-aa48-ed96b0f40862 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2021-09-09 11:23:34,998] INFO Expiring session 0x100822595950006, timeout of 18000ms exceeded (org.apache.zookeeper.server.ZooKeeperServer)
[2021-09-09 11:23:35,061] INFO [GroupCoordinator 0]: Member consumer-mygroup-1-9dadc61c-5e54-4cf1-9dcc-6a54fcf84e17 in group mygroup has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-09-09 11:23:35,106] INFO [GroupCoordinator 0]: Stabilized group mygroup generation 248 (__consumer_offsets-39) (kafka.coordinator.group.GroupCoordinator)
[2021-09-09 11:23:35,171] INFO [GroupCoordinator 0]: Assignment received from leader for group mygroup for generation 248 (kafka.coordinator.group.GroupCoordinator)
[2021-09-09 11:23:35,103] WARN fsync-ing the write ahead log in SyncThread:0 took 45128713ms which will adversely effect operation latency. File size is 67108880 bytes. See the ZooKeeper troubleshooting guide (org.apache.zookeeper.server.persistence.FileTxnLog)
[2021-09-09 11:23:35,232] WARN Client session timed out, have not heard from server in 45128992ms for sessionid 0x100822595950006 (org.apache.zookeeper.ClientCnxn)
[2021-09-09 11:23:35,232] INFO Client session timed out, have not heard from server in 45128992ms for sessionid 0x100822595950006, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2021-09-09 11:23:35,728] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2021-09-09 11:23:35,803] INFO [ZooKeeperClient Kafka server] Connected. (kafka.zookeeper.ZooKeeperClient)
[2021-09-09 11:23:37,092] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-09 11:23:37,093] INFO Socket connection established, initiating session, client: /0:0:0:0:0:0:0:1:55416, server: localhost/0:0:0:0:0:0:0:1:2181 (org.apache.zookeeper.ClientCnxn)
[2021-09-09 11:23:37,096] INFO Invalid session 0x100822595950006 for client /0:0:0:0:0:0:0:1:55416, probably expired (org.apache.zookeeper.server.ZooKeeperServer)
[2021-09-09 11:23:37,097] WARN Unable to reconnect to ZooKeeper service, session 0x100822595950006 has expired (org.apache.zookeeper.ClientCnxn)
[2021-09-09 11:23:37,097] INFO EventThread shut down for session: 0x100822595950006 (org.apache.zookeeper.ClientCnxn)
[2021-09-09 11:23:37,097] INFO Unable to reconnect to ZooKeeper service, session 0x100822595950006 has expired, closing socket connection (org.apache.zookeeper.ClientCnxn)
[2021-09-09 11:23:37,097] INFO [ZooKeeperClient Kafka server] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2021-09-09 11:23:38,002] INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181. (kafka.zookeeper.ZooKeeperClient)
[2021-09-09 11:23:38,016] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=18000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@6973b51b (org.apache.zookeeper.ZooKeeper)
[2021-09-09 11:23:38,027] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
[2021-09-09 11:23:38,028] INFO zookeeper.request.timeout value is 0. feature enabled= (org.apache.zookeeper.ClientCnxn)
[2021-09-09 11:23:38,081] INFO Creating /brokers/ids/0 (is it secure? false) (kafka.zk.KafkaZkClient)
[2021-09-09 11:23:38,082] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-09 11:23:38,102] INFO Socket connection established, initiating session, client: /127.0.0.1:59865, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn)
[2021-09-09 11:23:38,220] INFO Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x100822595950007, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
[2021-09-09 11:23:38,294] INFO Updated cache from existing FinalizedFeaturesAndEpoch(features=Features{}, epoch=0) to latest FinalizedFeaturesAndEpoch(features=Features{}, epoch=0). (kafka.server.FinalizedFeatureCache)
[2021-09-09 11:23:38,329] INFO Stat of the created znode at /brokers/ids/0 is: 420,420,1631166818279,1631166818279,1,0,0,72200691972898823,202,0,420
 (kafka.zk.KafkaZkClient)
[2021-09-09 11:23:38,344] INFO Registered broker 0 at path /brokers/ids/0 with addresses: PLAINTEXT://localhost:9092, czxid (broker epoch): 420 (kafka.zk.KafkaZkClient)
[2021-09-09 11:23:38,440] ERROR Failed to clean up log for __consumer_offsets-39 in dir D:\Workspace\SpringBoot\MB\Kafka\kafka\bin\windows\WorkspaceSpringBootMBKafkakafkadataKafka due to IOException (kafka.server.LogDirFailureChannel)
java.nio.file.FileSystemException: D:\Workspace\SpringBoot\MB\Kafka\kafka\bin\windows\WorkspaceSpringBootMBKafkakafkadataKafka\__consumer_offsets-39\00000000000000000000.timeindex.cleaned -> D:\Workspace\SpringBoot\MB\Kafka\kafka\bin\windows\WorkspaceSpringBootMBKafkakafkadataKafka\__consumer_offsets-39\00000000000000000000.timeindex.swap: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:917)
	at kafka.log.AbstractIndex.renameTo(AbstractIndex.scala:211)
	at kafka.log.LazyIndex$IndexValue.renameTo(LazyIndex.scala:155)
	at kafka.log.LazyIndex.$anonfun$renameTo$1(LazyIndex.scala:79)
	at kafka.log.LazyIndex.renameTo(LazyIndex.scala:79)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:497)
	at kafka.log.Log.$anonfun$replaceSegments$4(Log.scala:2355)
	at kafka.log.Log.$anonfun$replaceSegments$4$adapted(Log.scala:2355)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at kafka.log.Log.replaceSegments(Log.scala:2355)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:614)
	at kafka.log.Cleaner.$anonfun$doClean$6(LogCleaner.scala:539)
	at kafka.log.Cleaner.doClean(LogCleaner.scala:538)
	at kafka.log.Cleaner.clean(LogCleaner.scala:512)
	at kafka.log.LogCleaner$CleanerThread.cleanLog(LogCleaner.scala:381)
	at kafka.log.LogCleaner$CleanerThread.cleanFilthiestLog(LogCleaner.scala:353)
	at kafka.log.LogCleaner$CleanerThread.tryCleanFilthiestLog(LogCleaner.scala:333)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:322)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
	Suppressed: java.nio.file.FileSystemException: D:\Workspace\SpringBoot\MB\Kafka\kafka\bin\windows\WorkspaceSpringBootMBKafkakafkadataKafka\__consumer_offsets-39\00000000000000000000.timeindex.cleaned -> D:\Workspace\SpringBoot\MB\Kafka\kafka\bin\windows\WorkspaceSpringBootMBKafkakafkadataKafka\__consumer_offsets-39\00000000000000000000.timeindex.swap: The process cannot access the file because it is being used by another process.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:914)
		... 18 more
[2021-09-09 11:23:38,544] WARN [ReplicaManager broker=0] Stopping serving replicas in dir D:\Workspace\SpringBoot\MB\Kafka\kafka\bin\windows\WorkspaceSpringBootMBKafkakafkadataKafka (kafka.server.ReplicaManager)
[2021-09-09 11:23:38,634] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions HashSet(__consumer_offsets-22, __consumer_offsets-30, __consumer_offsets-25, __consumer_offsets-35, __consumer_offsets-13, __consumer_offsets-8, __consumer_offsets-21, __consumer_offsets-4, __consumer_offsets-27, __consumer_offsets-7, __consumer_offsets-9, mytopic-0, __consumer_offsets-46, __consumer_offsets-41, __consumer_offsets-33, __consumer_offsets-23, __consumer_offsets-49, __consumer_offsets-47, __consumer_offsets-16, __consumer_offsets-28, __consumer_offsets-31, __consumer_offsets-36, __consumer_offsets-42, __consumer_offsets-3, __consumer_offsets-18, __consumer_offsets-37, key-0, __consumer_offsets-15, __consumer_offsets-24, updateUser-0, __consumer_offsets-38, __consumer_offsets-17, __consumer_offsets-48, __consumer_offsets-19, __consumer_offsets-11, userDto-0, __consumer_offsets-2, __consumer_offsets-43, __consumer_offsets-6, __consumer_offsets-14, __consumer_offsets-20, __consumer_offsets-0, __consumer_offsets-44, __consumer_offsets-39, __consumer_offsets-12, __consumer_offsets-45, __consumer_offsets-1, __consumer_offsets-5, __consumer_offsets-26, __consumer_offsets-29, __consumer_offsets-34, __consumer_offsets-10, __consumer_offsets-32, __consumer_offsets-40) (kafka.server.ReplicaFetcherManager)
[2021-09-09 11:23:38,655] INFO [ReplicaAlterLogDirsManager on broker 0] Removed fetcher for partitions HashSet(__consumer_offsets-22, __consumer_offsets-30, __consumer_offsets-25, __consumer_offsets-35, __consumer_offsets-13, __consumer_offsets-8, __consumer_offsets-21, __consumer_offsets-4, __consumer_offsets-27, __consumer_offsets-7, __consumer_offsets-9, mytopic-0, __consumer_offsets-46, __consumer_offsets-41, __consumer_offsets-33, __consumer_offsets-23, __consumer_offsets-49, __consumer_offsets-47, __consumer_offsets-16, __consumer_offsets-28, __consumer_offsets-31, __consumer_offsets-36, __consumer_offsets-42, __consumer_offsets-3, __consumer_offsets-18, __consumer_offsets-37, key-0, __consumer_offsets-15, __consumer_offsets-24, updateUser-0, __consumer_offsets-38, __consumer_offsets-17, __consumer_offsets-48, __consumer_offsets-19, __consumer_offsets-11, userDto-0, __consumer_offsets-2, __consumer_offsets-43, __consumer_offsets-6, __consumer_offsets-14, __consumer_offsets-20, __consumer_offsets-0, __consumer_offsets-44, __consumer_offsets-39, __consumer_offsets-12, __consumer_offsets-45, __consumer_offsets-1, __consumer_offsets-5, __consumer_offsets-26, __consumer_offsets-29, __consumer_offsets-34, __consumer_offsets-10, __consumer_offsets-32, __consumer_offsets-40) (kafka.server.ReplicaAlterLogDirsManager)
[2021-09-09 11:23:38,850] ERROR Failed to clean up log for __consumer_offsets-39 in dir D:\Workspace\SpringBoot\MB\Kafka\kafka\bin\windows\WorkspaceSpringBootMBKafkakafkadataKafka due to IOException (kafka.server.LogDirFailureChannel)
java.nio.file.FileSystemException: D:\Workspace\SpringBoot\MB\Kafka\kafka\bin\windows\WorkspaceSpringBootMBKafkakafkadataKafka\__consumer_offsets-39\00000000000000000000.timeindex.cleaned: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
	at java.nio.file.Files.deleteIfExists(Files.java:1165)
	at kafka.log.Log$.deleteFileIfExists(Log.scala:2632)
	at kafka.log.LogSegment$.deleteIfExists(LogSegment.scala:676)
	at kafka.log.LogCleaner$.createNewCleanedSegment(LogCleaner.scala:455)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:567)
	at kafka.log.Cleaner.$anonfun$doClean$6(LogCleaner.scala:539)
	at kafka.log.Cleaner.doClean(LogCleaner.scala:538)
	at kafka.log.Cleaner.clean(LogCleaner.scala:512)
	at kafka.log.LogCleaner$CleanerThread.cleanLog(LogCleaner.scala:381)
	at kafka.log.LogCleaner$CleanerThread.cleanFilthiestLog(LogCleaner.scala:353)
	at kafka.log.LogCleaner$CleanerThread.tryCleanFilthiestLog(LogCleaner.scala:333)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:322)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-09-09 11:23:39,173] WARN [ReplicaManager broker=0] Broker 0 stopped fetcher for partitions __consumer_offsets-22,__consumer_offsets-30,__consumer_offsets-25,__consumer_offsets-35,__consumer_offsets-13,__consumer_offsets-8,__consumer_offsets-21,__consumer_offsets-4,__consumer_offsets-27,__consumer_offsets-7,__consumer_offsets-9,mytopic-0,__consumer_offsets-46,__consumer_offsets-41,__consumer_offsets-33,__consumer_offsets-23,__consumer_offsets-49,__consumer_offsets-47,__consumer_offsets-16,__consumer_offsets-28,__consumer_offsets-31,__consumer_offsets-36,__consumer_offsets-42,__consumer_offsets-3,__consumer_offsets-18,__consumer_offsets-37,key-0,__consumer_offsets-15,__consumer_offsets-24,updateUser-0,__consumer_offsets-38,__consumer_offsets-17,__consumer_offsets-48,__consumer_offsets-19,__consumer_offsets-11,userDto-0,__consumer_offsets-2,__consumer_offsets-43,__consumer_offsets-6,__consumer_offsets-14,__consumer_offsets-20,__consumer_offsets-0,__consumer_offsets-44,__consumer_offsets-39,__consumer_offsets-12,__consumer_offsets-45,__consumer_offsets-1,__consumer_offsets-5,__consumer_offsets-26,__consumer_offsets-29,__consumer_offsets-34,__consumer_offsets-10,__consumer_offsets-32,__consumer_offsets-40 and stopped moving logs for partitions  because they are in the failed log directory D:\Workspace\SpringBoot\MB\Kafka\kafka\bin\windows\WorkspaceSpringBootMBKafkakafkadataKafka. (kafka.server.ReplicaManager)
[2021-09-09 11:23:39,331] ERROR Failed to clean up log for __consumer_offsets-39 in dir D:\Workspace\SpringBoot\MB\Kafka\kafka\bin\windows\WorkspaceSpringBootMBKafkakafkadataKafka due to IOException (kafka.server.LogDirFailureChannel)
java.nio.file.FileSystemException: D:\Workspace\SpringBoot\MB\Kafka\kafka\bin\windows\WorkspaceSpringBootMBKafkakafkadataKafka\__consumer_offsets-39\00000000000000000000.timeindex.cleaned: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
	at java.nio.file.Files.deleteIfExists(Files.java:1165)
	at kafka.log.Log$.deleteFileIfExists(Log.scala:2632)
	at kafka.log.LogSegment$.deleteIfExists(LogSegment.scala:676)
	at kafka.log.LogCleaner$.createNewCleanedSegment(LogCleaner.scala:455)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:567)
	at kafka.log.Cleaner.$anonfun$doClean$6(LogCleaner.scala:539)
	at kafka.log.Cleaner.doClean(LogCleaner.scala:538)
	at kafka.log.Cleaner.clean(LogCleaner.scala:512)
	at kafka.log.LogCleaner$CleanerThread.cleanLog(LogCleaner.scala:381)
	at kafka.log.LogCleaner$CleanerThread.cleanFilthiestLog(LogCleaner.scala:353)
	at kafka.log.LogCleaner$CleanerThread.tryCleanFilthiestLog(LogCleaner.scala:333)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:322)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-09-09 11:23:39,563] WARN Stopping serving logs in dir D:\Workspace\SpringBoot\MB\Kafka\kafka\bin\windows\WorkspaceSpringBootMBKafkakafkadataKafka (kafka.log.LogManager)
[2021-09-09 11:23:39,772] ERROR Failed to clean up log for __consumer_offsets-39 in dir D:\Workspace\SpringBoot\MB\Kafka\kafka\bin\windows\WorkspaceSpringBootMBKafkakafkadataKafka due to IOException (kafka.server.LogDirFailureChannel)
java.nio.file.FileSystemException: D:\Workspace\SpringBoot\MB\Kafka\kafka\bin\windows\WorkspaceSpringBootMBKafkakafkadataKafka\__consumer_offsets-39\00000000000000000000.timeindex.cleaned: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
	at java.nio.file.Files.deleteIfExists(Files.java:1165)
	at kafka.log.Log$.deleteFileIfExists(Log.scala:2632)
	at kafka.log.LogSegment$.deleteIfExists(LogSegment.scala:676)
	at kafka.log.LogCleaner$.createNewCleanedSegment(LogCleaner.scala:455)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:567)
	at kafka.log.Cleaner.$anonfun$doClean$6(LogCleaner.scala:539)
	at kafka.log.Cleaner.doClean(LogCleaner.scala:538)
	at kafka.log.Cleaner.clean(LogCleaner.scala:512)
	at kafka.log.LogCleaner$CleanerThread.cleanLog(LogCleaner.scala:381)
	at kafka.log.LogCleaner$CleanerThread.cleanFilthiestLog(LogCleaner.scala:353)
	at kafka.log.LogCleaner$CleanerThread.tryCleanFilthiestLog(LogCleaner.scala:333)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:322)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-09-09 11:23:40,067] ERROR Shutdown broker because all log dirs in D:\Workspace\SpringBoot\MB\Kafka\kafka\bin\windows\WorkspaceSpringBootMBKafkakafkadataKafka have failed (kafka.log.LogManager)
[2021-09-09 11:23:40,768] WARN Exception causing close of session 0x100822595950007: An existing connection was forcibly closed by the remote host (org.apache.zookeeper.server.NIOServerCnxn)
[2021-09-09 11:23:59,955] INFO Expiring session 0x100822595950007, timeout of 18000ms exceeded (org.apache.zookeeper.server.ZooKeeperServer)
